from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('shop/', views.shop, name='shop'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('change-password/', views.change_password, name='change-password'),
    path('profile/', views.profile, name='profile'),
    path('forgot-password/', views.forgot_choice, name='forgot_password'),
    path('forgot-password/mobile/', views.forgot_password, name='forgot_password_mobile'),
    path('forgot-password/email/', views.forgot_password_email, name='forgot_password_email'),
    path('verify-otp/', views.verify_otp, name='verify_otp'),
    path('new-password/', views.new_password, name='new-password'),
    path('seller-add-product/', views.seller_add_product, name='seller-add-product'),
    path('seller-view-products/', views.seller_view_products, name='seller-view-products'),
    path('seller-product-details/<int:pk>/', views.seller_product_details, name='seller-product-details'),
    path('product-details/<int:pk>/', views.product_details, name='product-details'),
    path('seller-edit-product/<int:pk>/', views.seller_edit_product, name='seller-edit-product'),
    path('seller-delete-product/<int:pk>/', views.seller_delete_product, name='seller-delete-product'),
    path('add-to-wishlist/<int:pk>/', views.add_to_wishlist, name='add-to-wishlist'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('remove-from-wishlist/<int:pk>/', views.remove_from_wishlist, name='remove-from-wishlist'),
    path('add-to-cart/<int:pk>/', views.add_to_cart, name='add-to-cart'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('update-cart-qty/<int:pk>/<str:action>/', views.update_cart_qty, name='update-cart-qty'),
    path('remove-from-cart/<int:pk>/', views.remove_from_cart, name='remove-from-cart'),
     path('create-checkout-session/', views.create_checkout_session, name='payment'),
    path('success.html/', views.success,name='success'),
    path('cancel.html/', views.cancel,name='cancel'),
    path("myorder/",views.myorder,name='myorder'),
]